# This is a basic workflow to help you get started with Actions

name: deploy

on:
  push:
    branches: [main]
    tags: [v*]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      AUTODEPLOY_TAG: ${{ secrets.AUTODEPLOY_TAG }}
      AUTODEPLOY_URL: https://dfusion.auto.gnosisdev.com/services/dfusion-v2-lpbook-prototype-mainnet/rollout
      AUTODEPLOY_TOKEN: ${{ secrets.AUTODEPLOY_TOKEN }}
      DOCKERHUB_PROJECT: lpbook-prototype
      DOCKER_NAME: ${{ secrets.DOCKER_NAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - run: docker/deploy.sh ${GITHUB_REF#refs/*/}
